import type { Metadata } from "next";
import {yekan} from '@/utils/fonts'
import "./globals.css";
import Layout from "@/layout/Layout";
import NextAuthProvider from "@/providers/NextAuthProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>
      <Layout>
        {children}
      </Layout>
        </NextAuthProvider>
        </body>
    </html>
  );
}
